export const PATHS = {
	AUTH: {
		LOGIN: "/login",
		FORGOT_PASSWORD: "/forgot-password",
	},
	DASHBOARD: "/dashboard",
	ACADEMICS: {
		ROOT: "/academics",
		CLASSES: "/academics/classes",
		SUBJECTS: "/academics/subjects",
		SYLLABUS: "/academics/syllabus",
		TIMETABLE: "/academics/timetable",
		HOMEWORK: "/academics/homework",
		ONLINE_CLASSES: "/academics/online-classes",
	},
	ADMISSION: {
		ROOT: "/admission",
		NEW: "/admission/new",
		LIST: "/admission/list",
		PORTAL: "/admission/portal",
		TRANSFER: "/admission/transfer",
		SETTINGS: "/admission/settings",
	},
	STUDENTS: {
		ROOT: "/students",
		DIRECTORY: "/students/directory",
		ATTENDANCE: "/students/attendance",
		PROFILE: "/students/profile",
		PROMOTION: "/students/promotion",
		ID_CARDS: "/students/id-cards",
		CERTIFICATES: "/students/certificates",
		BEHAVIOR: "/students/behavior",
	},
	STAFF: {
		ROOT: "/staff",
		DIRECTORY: "/staff/directory",
		ATTENDANCE: "/staff/attendance",
		DEPARTMENTS: "/staff/departments",
		PERFORMANCE: "/staff/performance",
	},
	PARENTS: {
		ROOT: "/parents",
		DIRECTORY: "/parents/directory",
		PORTAL: "/parents/portal",
	},
	FINANCE: {
		ROOT: "/finance",
		FEES: "/finance/fees",
		EXPENSES: "/finance/expenses",
		PAYROLL: "/finance/payroll",
		LEDGER: "/finance/ledger",
		SCHOLARSHIPS: "/finance/scholarships",
		BUDGET: "/finance/budget",
		VOUCHERS: "/finance/vouchers",
		BANK_ACCOUNTS: "/finance/bank-accounts",
	},
	HR: {
		ROOT: "/hr",
		LEAVE: "/hr/leave",
		LOAN: "/hr/loan",
		APPRAISAL: "/hr/appraisal",
	},
	EXAMINATIONS: {
		ROOT: "/examinations",
		SCHEDULE: "/examinations/schedule",
		MARKS: "/examinations/marks",
		RESULTS: "/examinations/results",
		REPORT_CARDS: "/examinations/report-cards",
		QUESTION_BANK: "/examinations/question-bank",
		SETTINGS: "/examinations/settings",
	},
	LIBRARY: {
		ROOT: "/library",
		CATALOG: "/library/catalog",
		ISSUE_RETURN: "/library/issue-return",
		FINES: "/library/fines",
		REPORTS: "/library/reports",
	},
	COMMUNICATIONS: {
		ROOT: "/communications",
		ANNOUNCEMENTS: "/communications/announcements",
		NOTICE_BOARD: "/communications/notice-board",
		MESSAGES: "/communications/messages",
		COMPLAINTS: "/communications/complaints",
	},
	EVENTS: {
		ROOT: "/events",
		SCHEDULING: "/events/scheduling",
		PARTICIPANTS: "/events/participants",
		GALLERY: "/events/gallery",
	},
	TRANSPORT: {
		ROOT: "/transport",
		ROUTES: "/transport/routes",
		VEHICLES: "/transport/vehicles",
		ASSIGNMENT: "/transport/assignment",
		ATTENDANCE: "/transport/attendance",
	},
	CANTEEN: {
		ROOT: "/canteen",
		MENU: "/canteen/menu",
		SALES: "/canteen/sales",
		EXPENSE: "/canteen/expense",
	},
	REPORTS: {
		ROOT: "/reports",
		ACADEMIC: "/reports/academic",
		FINANCE: "/reports/finance",
		STUDENT: "/reports/student",
		SCHEDULED: "/reports/scheduled",
	},
	ROLES: {
		ROOT: "/roles",
		MANAGEMENT: "/roles/management",
		MATRIX: "/roles/matrix",
	},
	SETTINGS: {
		ROOT: "/settings",
		PROFILE: "/settings/profile",
		USERS: "/settings/users",
		INTEGRATIONS: "/settings/integrations",
		LOCALIZATION: "/settings/localization",
		BACKUP: "/settings/backup",
		AUDIT: "/settings/audit",
	},
} as const;
