export const PERMISSIONS = {
  DASHBOARD: {
    VIEW: 'dashboard.view',
  },
  ACADEMICS: {
    VIEW: 'academics.view',
    CLASSES: 'academics.classes.view',
    SUBJECTS: 'academics.subjects.view',
    SYLLABUS: 'academics.syllabus.view',
    TIMETABLE: 'academics.timetable.view',
    HOMEWORK: 'academics.homework.view',
    ONLINE_CLASSES: 'academics.online_classes.view',
  },
  ADMISSION: {
    VIEW: 'admission.view',
    NEW: 'admission.new.view',
    LIST: 'admission.list.view',
    PORTAL: 'admission.portal.view',
    TRANSFER: 'admission.transfer.view',
    SETTINGS: 'admission.settings.view',
  },
  STUDENTS: {
    VIEW: 'students.view',
    DIRECTORY: 'students.directory.view',
    ATTENDANCE: 'students.attendance.view',
    PROFILE: 'students.profile.view',
    PROMOTION: 'students.promotion.view',
    ID_CARDS: 'students.id_cards.view',
    CERTIFICATES: 'students.certificates.view',
    BEHAVIOR: 'students.behavior.view',
  },
  STAFF: {
    VIEW: 'staff.view',
    DIRECTORY: 'staff.directory.view',
    ATTENDANCE: 'staff.attendance.view',
    DEPARTMENTS: 'staff.departments.view',
    PERFORMANCE: 'staff.performance.view',
  },
  PARENTS: {
    VIEW: 'parents.view',
    DIRECTORY: 'parents.directory.view',
    PORTAL: 'parents.portal.view',
  },
  FINANCE: {
    VIEW: 'finance.view',
    FEES: 'finance.fees.view',
    EXPENSES: 'finance.expenses.view',
    PAYROLL: 'finance.payroll.view',
    LEDGER: 'finance.ledger.view',
    SCHOLARSHIPS: 'finance.scholarships.view',
    BUDGET: 'finance.budget.view',
    VOUCHERS: 'finance.vouchers.view',
    BANK_ACCOUNTS: 'finance.bank_accounts.view',
  },
  HR: {
    VIEW: 'hr.view',
    LEAVE: 'hr.leave.view',
    LOAN: 'hr.loan.view',
    APPRAISAL: 'hr.appraisal.view',
  },
  EXAMINATIONS: {
    VIEW: 'examinations.view',
    SCHEDULE: 'examinations.schedule.view',
    MARKS: 'examinations.marks.view',
    RESULTS: 'examinations.results.view',
    REPORT_CARDS: 'examinations.report_cards.view',
    QUESTION_BANK: 'examinations.question_bank.view',
    SETTINGS: 'examinations.settings.view',
  },
  LIBRARY: {
    VIEW: 'library.view',
    CATALOG: 'library.catalog.view',
    ISSUE_RETURN: 'library.issue_return.view',
    FINES: 'library.fines.view',
    REPORTS: 'library.reports.view',
  },
  COMMUNICATIONS: {
    VIEW: 'communications.view',
    ANNOUNCEMENTS: 'communications.announcements.view',
    NOTICE_BOARD: 'communications.notice_board.view',
    MESSAGES: 'communications.messages.view',
    COMPLAINTS: 'communications.complaints.view',
  },
  EVENTS: {
    VIEW: 'events.view',
    SCHEDULING: 'events.scheduling.view',
    PARTICIPANTS: 'events.participants.view',
    GALLERY: 'events.gallery.view',
  },
  TRANSPORT: {
    VIEW: 'transport.view',
    ROUTES: 'transport.routes.view',
    VEHICLES: 'transport.vehicles.view',
    ASSIGNMENT: 'transport.assignment.view',
    ATTENDANCE: 'transport.attendance.view',
  },
  CANTEEN: {
    VIEW: 'canteen.view',
    MENU: 'canteen.menu.view',
    SALES: 'canteen.sales.view',
    EXPENSE: 'canteen.expense.view',
  },
  REPORTS: {
    VIEW: 'reports.view',
    ACADEMIC: 'reports.academic.view',
    FINANCE: 'reports.finance.view',
    STUDENT: 'reports.student.view',
    SCHEDULED: 'reports.scheduled.view',
  },
  ROLES: {
    VIEW: 'roles.view',
    MANAGEMENT: 'roles.management.view',
    MATRIX: 'roles.matrix.view',
  },
  SETTINGS: {
    VIEW: 'settings.view',
    PROFILE: 'settings.profile.view',
    USERS: 'settings.users.view',
    INTEGRATIONS: 'settings.integrations.view',
    LOCALIZATION: 'settings.localization.view',
    BACKUP: 'settings.backup.view',
    AUDIT: 'settings.audit.view',
  },
} as const;
