export const ROLES = {
	DEVELOPER: "DEVELOPER",
	SUPER_ADMIN: "SUPER_ADMIN",
	SCHOOL_ADMIN: "SCHOOL_ADMIN",
	SCHOOL_STAFF: "SCHOOL_STAFF",
	TEACHER: "TEACHER",
	STUDENT: "STUDENT",
	PARENT: "PARENT",
};
