import {
	Activity,
	AlarmClockCheck,
	AlertCircle,
	ArrowRightLeft,
	Award,
	Banknote,
	BarChart3,
	BookMarked,
	BookOpen,
	BookType,
	Briefcase,
	Building2,
	Bus,
	CalendarDays,
	Clipboard,
	ClipboardList,
	Coins,
	Database,
	DoorOpen,
	FileBadge2,
	Gift,
	Globe,
	GraduationCap,
	HeartHandshake,
	History,
	IdCard,
	Landmark,
	Laptop,
	LayoutDashboard,
	Library,
	Link,
	Megaphone,
	MessageSquare,
	Network,
	PieChart,
	Receipt,
	School,
	Settings,
	ShieldCheck,
	Store,
	TrendingUp,
	User,
	UserCheck,
	Users,
	UsersRound,
} from "lucide-react";

import { PATHS } from "./paths.config";
import { PERMISSIONS } from "./permissions.config";

export type SidebarMenuType = {
	id: string;
	name: string;
	path: string;
	icon: React.ElementType;
	permissions: string[];
	matchPaths: string[];
	resetStore?: () => void;
	children?: SidebarMenuType[];
};

export const SidebarMenu: SidebarMenuType[] = [
	{
		id: "dashboard",
		name: "Dashboard",
		path: PATHS.DASHBOARD,
		icon: LayoutDashboard,
		permissions: [PERMISSIONS.DASHBOARD.VIEW],
		matchPaths: [PATHS.DASHBOARD],
	},
	{
		id: "academics",
		name: "Academics",
		path: PATHS.ACADEMICS.ROOT,
		icon: BookOpen,
		permissions: [PERMISSIONS.ACADEMICS.VIEW],
		matchPaths: [PATHS.ACADEMICS.ROOT],
		children: [
			{
				id: "academics_classes",
				name: "Classes & Sections",
				path: PATHS.ACADEMICS.CLASSES.ROOT,
				icon: Building2,
				permissions: [PERMISSIONS.ACADEMICS.CLASSES.VIEW],
				matchPaths: [PATHS.ACADEMICS.CLASSES.ROOT],
			},
			{
				id: "academics_subjects",
				name: "Subjects",
				path: PATHS.ACADEMICS.SUBJECTS.ROOT,
				icon: BookOpen,
				permissions: [PERMISSIONS.ACADEMICS.SUBJECTS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SUBJECTS.ROOT],
			},
			{
				id: "academics_syllabus",
				name: "Syllabus",
				path: PATHS.ACADEMICS.SYLLABUS.ROOT,
				icon: FileBadge2,
				permissions: [PERMISSIONS.ACADEMICS.SYLLABUS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SYLLABUS.ROOT],
			},
			{
				id: "academics_timetable",
				name: "Class Timetable",
				path: PATHS.ACADEMICS.TIMETABLE.ROOT,
				icon: AlarmClockCheck,
				permissions: [PERMISSIONS.ACADEMICS.TIMETABLE.VIEW],
				matchPaths: [PATHS.ACADEMICS.TIMETABLE.ROOT],
			},
			{
				id: "academics_homework",
				name: "Homework & Assignments",
				path: PATHS.ACADEMICS.HOMEWORK.ROOT,
				icon: BookMarked,
				permissions: [PERMISSIONS.ACADEMICS.HOMEWORK.VIEW],
				matchPaths: [PATHS.ACADEMICS.HOMEWORK.ROOT],
			},
			{
				id: "academics_online_classes",
				name: "Online Classes",
				path: PATHS.ACADEMICS.ONLINE_CLASSES.ROOT,
				icon: Laptop,
				permissions: [PERMISSIONS.ACADEMICS.ONLINE_CLASSES.VIEW],
				matchPaths: [PATHS.ACADEMICS.ONLINE_CLASSES.ROOT],
			},
			{
				id: "academics_shifts",
				name: "Shifts",
				path: PATHS.ACADEMICS.SHIFTS.ROOT,
				icon: AlarmClockCheck,
				permissions: [PERMISSIONS.ACADEMICS.SHIFTS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SHIFTS.ROOT],
			},
		],
	},
	{
		id: "admission",
		name: "Admission",
		path: PATHS.ADMISSION.ROOT,
		icon: DoorOpen,
		permissions: [PERMISSIONS.ADMISSION.VIEW],
		matchPaths: [PATHS.ADMISSION.ROOT],
		children: [
			{
				id: "admission_new",
				name: "New Admission",
				path: PATHS.ADMISSION.NEW.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.ADMISSION.NEW.VIEW],
				matchPaths: [PATHS.ADMISSION.NEW.ROOT],
			},
			{
				id: "admission_list",
				name: "Application List",
				path: PATHS.ADMISSION.LIST.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.ADMISSION.LIST.VIEW],
				matchPaths: [PATHS.ADMISSION.LIST.ROOT],
			},
			{
				id: "admission_portal",
				name: "Online Portal",
				path: PATHS.ADMISSION.PORTAL.ROOT,
				icon: Globe,
				permissions: [PERMISSIONS.ADMISSION.PORTAL.VIEW],
				matchPaths: [PATHS.ADMISSION.PORTAL.ROOT],
			},
			{
				id: "admission_transfer",
				name: "Transfer Students",
				path: PATHS.ADMISSION.TRANSFER.ROOT,
				icon: ArrowRightLeft,
				permissions: [PERMISSIONS.ADMISSION.TRANSFER.VIEW],
				matchPaths: [PATHS.ADMISSION.TRANSFER.ROOT],
			},
			{
				id: "admission_settings",
				name: "Admission Settings",
				path: PATHS.ADMISSION.SETTINGS.ROOT,
				icon: Settings,
				permissions: [PERMISSIONS.ADMISSION.SETTINGS.VIEW],
				matchPaths: [PATHS.ADMISSION.SETTINGS.ROOT],
			},
		],
	},
	{
		id: "students",
		name: "Students",
		path: PATHS.STUDENTS.ROOT,
		icon: GraduationCap,
		permissions: [PERMISSIONS.STUDENTS.VIEW],
		matchPaths: [PATHS.STUDENTS.ROOT],
		children: [
			{
				id: "students_directory",
				name: "Student Directory",
				path: PATHS.STUDENTS.DIRECTORY.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.STUDENTS.DIRECTORY.VIEW],
				matchPaths: [PATHS.STUDENTS.DIRECTORY.ROOT],
			},
			{
				id: "students_attendance",
				name: "Attendance",
				path: PATHS.STUDENTS.ATTENDANCE.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.STUDENTS.ATTENDANCE.VIEW],
				matchPaths: [PATHS.STUDENTS.ATTENDANCE.ROOT],
			},
			{
				id: "students_profile",
				name: "Student Profile",
				path: PATHS.STUDENTS.PROFILE.ROOT,
				icon: User,
				permissions: [PERMISSIONS.STUDENTS.PROFILE.VIEW],
				matchPaths: [PATHS.STUDENTS.PROFILE.ROOT],
			},
			{
				id: "students_promotion",
				name: "Class Promotion",
				path: PATHS.STUDENTS.PROMOTION.ROOT,
				icon: TrendingUp,
				permissions: [PERMISSIONS.STUDENTS.PROMOTION.VIEW],
				matchPaths: [PATHS.STUDENTS.PROMOTION.ROOT],
			},
			{
				id: "students_id_cards",
				name: "ID Cards",
				path: PATHS.STUDENTS.ID_CARDS.ROOT,
				icon: IdCard,
				permissions: [PERMISSIONS.STUDENTS.ID_CARDS.VIEW],
				matchPaths: [PATHS.STUDENTS.ID_CARDS.ROOT],
			},
			{
				id: "students_certificates",
				name: "Certificates",
				path: PATHS.STUDENTS.CERTIFICATES.ROOT,
				icon: Award,
				permissions: [PERMISSIONS.STUDENTS.CERTIFICATES.VIEW],
				matchPaths: [PATHS.STUDENTS.CERTIFICATES.ROOT],
			},
			{
				id: "students_behavior",
				name: "Behavior & Counseling",
				path: PATHS.STUDENTS.BEHAVIOR.ROOT,
				icon: HeartHandshake,
				permissions: [PERMISSIONS.STUDENTS.BEHAVIOR.VIEW],
				matchPaths: [PATHS.STUDENTS.BEHAVIOR.ROOT],
			},
		],
	},
	{
		id: "staff",
		name: "Staff & Teachers",
		path: PATHS.STAFF.ROOT,
		icon: Users,
		permissions: [PERMISSIONS.STAFF.VIEW],
		matchPaths: [PATHS.STAFF.ROOT],
		children: [
			{
				id: "staff_directory",
				name: "Staff Directory",
				path: PATHS.STAFF.DIRECTORY.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.STAFF.DIRECTORY.VIEW],
				matchPaths: [PATHS.STAFF.DIRECTORY.ROOT],
			},
			{
				id: "staff_teachers",
				name: "Teacher Directory",
				path: PATHS.STAFF.TEACHERS.ROOT,
				icon: UsersRound,
				permissions: [PERMISSIONS.STAFF.TEACHERS.VIEW],
				matchPaths: [PATHS.STAFF.TEACHERS.ROOT],
			},
			{
				id: "staff_attendance",
				name: "Staff Attendance",
				path: PATHS.STAFF.ATTENDANCE.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.STAFF.ATTENDANCE.VIEW],
				matchPaths: [PATHS.STAFF.ATTENDANCE.ROOT],
			},
			{
				id: "staff_departments",
				name: "Departments",
				path: PATHS.STAFF.DEPARTMENTS.ROOT,
				icon: Network,
				permissions: [PERMISSIONS.STAFF.DEPARTMENTS.VIEW],
				matchPaths: [PATHS.STAFF.DEPARTMENTS.ROOT],
			},
			{
				id: "staff_performance",
				name: "Teacher Performance",
				path: PATHS.STAFF.PERFORMANCE.ROOT,
				icon: Activity,
				permissions: [PERMISSIONS.STAFF.PERFORMANCE.VIEW],
				matchPaths: [PATHS.STAFF.PERFORMANCE.ROOT],
			},
		],
	},
	{
		id: "parents",
		name: "Parents",
		path: PATHS.PARENTS.ROOT,
		icon: UsersRound,
		permissions: [PERMISSIONS.PARENTS.VIEW],
		matchPaths: [PATHS.PARENTS.ROOT],
		children: [
			{
				id: "parents_directory",
				name: "Parent Directory",
				path: PATHS.PARENTS.DIRECTORY.ROOT,
				icon: UsersRound,
				permissions: [PERMISSIONS.PARENTS.DIRECTORY.VIEW],
				matchPaths: [PATHS.PARENTS.DIRECTORY.ROOT],
			},
			{
				id: "parents_portal",
				name: "Portal Access",
				path: PATHS.PARENTS.PORTAL.ROOT,
				icon: Laptop,
				permissions: [PERMISSIONS.PARENTS.PORTAL.VIEW],
				matchPaths: [PATHS.PARENTS.PORTAL.ROOT],
			},
		],
	},
	{
		id: "finance",
		name: "Finance",
		path: PATHS.FINANCE.ROOT,
		icon: Banknote,
		permissions: [PERMISSIONS.FINANCE.VIEW],
		matchPaths: [PATHS.FINANCE.ROOT],
		children: [
			{
				id: "finance_fees",
				name: "Fee Collection",
				path: PATHS.FINANCE.FEES.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.FINANCE.FEES.VIEW],
				matchPaths: [PATHS.FINANCE.FEES.ROOT],
			},
			{
				id: "finance_expenses",
				name: "Expenses",
				path: PATHS.FINANCE.EXPENSES.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.FINANCE.EXPENSES.VIEW],
				matchPaths: [PATHS.FINANCE.EXPENSES.ROOT],
			},
			{
				id: "finance_payroll",
				name: "Payroll",
				path: PATHS.FINANCE.PAYROLL.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.FINANCE.PAYROLL.VIEW],
				matchPaths: [PATHS.FINANCE.PAYROLL.ROOT],
			},
			{
				id: "finance_ledger",
				name: "Student Ledger",
				path: PATHS.FINANCE.LEDGER.ROOT,
				icon: BookType,
				permissions: [PERMISSIONS.FINANCE.LEDGER.VIEW],
				matchPaths: [PATHS.FINANCE.LEDGER.ROOT],
			},
			{
				id: "finance_scholarships",
				name: "Scholarships & Waivers",
				path: PATHS.FINANCE.SCHOLARSHIPS.ROOT,
				icon: Gift,
				permissions: [PERMISSIONS.FINANCE.SCHOLARSHIPS.VIEW],
				matchPaths: [PATHS.FINANCE.SCHOLARSHIPS.ROOT],
			},
			{
				id: "finance_budget",
				name: "Budget Planning",
				path: PATHS.FINANCE.BUDGET.ROOT,
				icon: PieChart,
				permissions: [PERMISSIONS.FINANCE.BUDGET.VIEW],
				matchPaths: [PATHS.FINANCE.BUDGET.ROOT],
			},
			{
				id: "finance_vouchers",
				name: "Voucher Management",
				path: PATHS.FINANCE.VOUCHERS.ROOT,
				icon: Receipt,
				permissions: [PERMISSIONS.FINANCE.VOUCHERS.VIEW],
				matchPaths: [PATHS.FINANCE.VOUCHERS.ROOT],
			},
			{
				id: "finance_bank_accounts",
				name: "Bank Accounts",
				path: PATHS.FINANCE.BANK_ACCOUNTS.ROOT,
				icon: Landmark,
				permissions: [PERMISSIONS.FINANCE.BANK_ACCOUNTS.VIEW],
				matchPaths: [PATHS.FINANCE.BANK_ACCOUNTS.ROOT],
			},
		],
	},
	{
		id: "hr",
		name: "HR Management",
		path: PATHS.HR.ROOT,
		icon: Briefcase,
		permissions: [PERMISSIONS.HR.VIEW],
		matchPaths: [PATHS.HR.ROOT],
		children: [
			{
				id: "hr_leave",
				name: "Leave Management",
				path: PATHS.HR.LEAVE.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.HR.LEAVE.VIEW],
				matchPaths: [PATHS.HR.LEAVE.ROOT],
			},
			{
				id: "hr_loan",
				name: "Loan & Advance",
				path: PATHS.HR.LOAN.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.HR.LOAN.VIEW],
				matchPaths: [PATHS.HR.LOAN.ROOT],
			},
			{
				id: "hr_appraisal",
				name: "Performance Appraisal",
				path: PATHS.HR.APPRAISAL.ROOT,
				icon: Activity,
				permissions: [PERMISSIONS.HR.APPRAISAL.VIEW],
				matchPaths: [PATHS.HR.APPRAISAL.ROOT],
			},
		],
	},
	{
		id: "examinations",
		name: "Examination & Results",
		path: PATHS.EXAMINATIONS.ROOT,
		icon: ClipboardList,
		permissions: [PERMISSIONS.EXAMINATIONS.VIEW],
		matchPaths: [PATHS.EXAMINATIONS.ROOT],
		children: [
			{
				id: "examinations_schedule",
				name: "Exam Schedule",
				path: PATHS.EXAMINATIONS.SCHEDULE.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.EXAMINATIONS.SCHEDULE.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.SCHEDULE.ROOT],
			},
			{
				id: "examinations_marks",
				name: "Mark Entry",
				path: PATHS.EXAMINATIONS.MARKS.ROOT,
				icon: FileBadge2,
				permissions: [PERMISSIONS.EXAMINATIONS.MARKS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.MARKS.ROOT],
			},
			{
				id: "examinations_results",
				name: "Result Processing",
				path: PATHS.EXAMINATIONS.RESULTS.ROOT,
				icon: Activity,
				permissions: [PERMISSIONS.EXAMINATIONS.RESULTS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.RESULTS.ROOT],
			},
			{
				id: "examinations_report_cards",
				name: "Report Cards",
				path: PATHS.EXAMINATIONS.REPORT_CARDS.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.EXAMINATIONS.REPORT_CARDS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.REPORT_CARDS.ROOT],
			},
			{
				id: "examinations_question_bank",
				name: "Question Bank",
				path: PATHS.EXAMINATIONS.QUESTION_BANK.ROOT,
				icon: BookOpen,
				permissions: [PERMISSIONS.EXAMINATIONS.QUESTION_BANK.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.QUESTION_BANK.ROOT],
			},
			{
				id: "examinations_settings",
				name: "Exam Settings",
				path: PATHS.EXAMINATIONS.SETTINGS.ROOT,
				icon: Settings,
				permissions: [PERMISSIONS.EXAMINATIONS.SETTINGS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.SETTINGS.ROOT],
			},
		],
	},
	{
		id: "library",
		name: "Library",
		path: PATHS.LIBRARY.ROOT,
		icon: Library,
		permissions: [PERMISSIONS.LIBRARY.VIEW],
		matchPaths: [PATHS.LIBRARY.ROOT],
		children: [
			{
				id: "library_catalog",
				name: "Book Catalog",
				path: PATHS.LIBRARY.CATALOG.ROOT,
				icon: BookOpen,
				permissions: [PERMISSIONS.LIBRARY.CATALOG.VIEW],
				matchPaths: [PATHS.LIBRARY.CATALOG.ROOT],
			},
			{
				id: "library_issue_return",
				name: "Issue & Return",
				path: PATHS.LIBRARY.ISSUE_RETURN.ROOT,
				icon: ArrowRightLeft,
				permissions: [PERMISSIONS.LIBRARY.ISSUE_RETURN.VIEW],
				matchPaths: [PATHS.LIBRARY.ISSUE_RETURN.ROOT],
			},
			{
				id: "library_fines",
				name: "Fine Management",
				path: PATHS.LIBRARY.FINES.ROOT,
				icon: Coins,
				permissions: [PERMISSIONS.LIBRARY.FINES.VIEW],
				matchPaths: [PATHS.LIBRARY.FINES.ROOT],
			},
			{
				id: "library_reports",
				name: "Library Reports",
				path: PATHS.LIBRARY.REPORTS.ROOT,
				icon: BarChart3,
				permissions: [PERMISSIONS.LIBRARY.REPORTS.VIEW],
				matchPaths: [PATHS.LIBRARY.REPORTS.ROOT],
			},
		],
	},
	{
		id: "communications",
		name: "Communications",
		path: PATHS.COMMUNICATIONS.ROOT,
		icon: Megaphone,
		permissions: [PERMISSIONS.COMMUNICATIONS.VIEW],
		matchPaths: [PATHS.COMMUNICATIONS.ROOT],
		children: [
			{
				id: "communications_announcements",
				name: "Announcements",
				path: PATHS.COMMUNICATIONS.ANNOUNCEMENTS.ROOT,
				icon: Megaphone,
				permissions: [PERMISSIONS.COMMUNICATIONS.ANNOUNCEMENTS.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.ANNOUNCEMENTS.ROOT],
			},
			{
				id: "communications_notice_board",
				name: "Notice Board",
				path: PATHS.COMMUNICATIONS.NOTICE_BOARD.ROOT,
				icon: Clipboard,
				permissions: [PERMISSIONS.COMMUNICATIONS.NOTICE_BOARD.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.NOTICE_BOARD.ROOT],
			},
			{
				id: "communications_messages",
				name: "Parent-Teacher Messaging",
				path: PATHS.COMMUNICATIONS.MESSAGES.ROOT,
				icon: MessageSquare,
				permissions: [PERMISSIONS.COMMUNICATIONS.MESSAGES.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.MESSAGES.ROOT],
			},
			{
				id: "communications_complaints",
				name: "Complaints & Feedback",
				path: PATHS.COMMUNICATIONS.COMPLAINTS.ROOT,
				icon: AlertCircle,
				permissions: [PERMISSIONS.COMMUNICATIONS.COMPLAINTS.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.COMPLAINTS.ROOT],
			},
		],
	},
	{
		id: "events",
		name: "Events Management",
		path: PATHS.EVENTS.ROOT,
		icon: CalendarDays,
		permissions: [PERMISSIONS.EVENTS.VIEW],
		matchPaths: [PATHS.EVENTS.ROOT],
		children: [
			{
				id: "events_scheduling",
				name: "Event Scheduling",
				path: PATHS.EVENTS.SCHEDULING.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.EVENTS.SCHEDULING.VIEW],
				matchPaths: [PATHS.EVENTS.SCHEDULING.ROOT],
			},
			{
				id: "events_participants",
				name: "Participant Management",
				path: PATHS.EVENTS.PARTICIPANTS.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.EVENTS.PARTICIPANTS.VIEW],
				matchPaths: [PATHS.EVENTS.PARTICIPANTS.ROOT],
			},
			{
				id: "events_gallery",
				name: "Event Gallery",
				path: PATHS.EVENTS.GALLERY.ROOT,
				icon: FileBadge2,
				permissions: [PERMISSIONS.EVENTS.GALLERY.VIEW],
				matchPaths: [PATHS.EVENTS.GALLERY.ROOT],
			},
		],
	},
	{
		id: "transport",
		name: "Transport Management",
		path: PATHS.TRANSPORT.ROOT,
		icon: Bus,
		permissions: [PERMISSIONS.TRANSPORT.VIEW],
		matchPaths: [PATHS.TRANSPORT.ROOT],
		children: [
			{
				id: "transport_routes",
				name: "Route Management",
				path: PATHS.TRANSPORT.ROUTES.ROOT,
				icon: Network,
				permissions: [PERMISSIONS.TRANSPORT.ROUTES.VIEW],
				matchPaths: [PATHS.TRANSPORT.ROUTES.ROOT],
			},
			{
				id: "transport_vehicles",
				name: "Vehicle Management",
				path: PATHS.TRANSPORT.VEHICLES.ROOT,
				icon: Bus,
				permissions: [PERMISSIONS.TRANSPORT.VEHICLES.VIEW],
				matchPaths: [PATHS.TRANSPORT.VEHICLES.ROOT],
			},
			{
				id: "transport_assignment",
				name: "Student Assignment",
				path: PATHS.TRANSPORT.ASSIGNMENT.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.TRANSPORT.ASSIGNMENT.VIEW],
				matchPaths: [PATHS.TRANSPORT.ASSIGNMENT.ROOT],
			},
			{
				id: "transport_attendance",
				name: "Transport Attendance",
				path: PATHS.TRANSPORT.ATTENDANCE.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.TRANSPORT.ATTENDANCE.VIEW],
				matchPaths: [PATHS.TRANSPORT.ATTENDANCE.ROOT],
			},
		],
	},
	{
		id: "canteen",
		name: "Canteen / Tuck Shop",
		path: PATHS.CANTEEN.ROOT,
		icon: Store,
		permissions: [PERMISSIONS.CANTEEN.VIEW],
		matchPaths: [PATHS.CANTEEN.ROOT],
		children: [
			{
				id: "canteen_menu",
				name: "Menu Management",
				path: PATHS.CANTEEN.MENU.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.CANTEEN.MENU.VIEW],
				matchPaths: [PATHS.CANTEEN.MENU.ROOT],
			},
			{
				id: "canteen_sales",
				name: "Sales Tracking",
				path: PATHS.CANTEEN.SALES.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.CANTEEN.SALES.VIEW],
				matchPaths: [PATHS.CANTEEN.SALES.ROOT],
			},
			{
				id: "canteen_expense",
				name: "Canteen Expense",
				path: PATHS.CANTEEN.EXPENSE.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.CANTEEN.EXPENSE.VIEW],
				matchPaths: [PATHS.CANTEEN.EXPENSE.ROOT],
			},
		],
	},
	{
		id: "reports",
		name: "Reports & Analytics",
		path: PATHS.REPORTS.ROOT,
		icon: BarChart3,
		permissions: [PERMISSIONS.REPORTS.VIEW],
		matchPaths: [PATHS.REPORTS.ROOT],
		children: [
			{
				id: "reports_academic",
				name: "Academic Reports",
				path: PATHS.REPORTS.ACADEMIC.ROOT,
				icon: BarChart3,
				permissions: [PERMISSIONS.REPORTS.ACADEMIC.VIEW],
				matchPaths: [PATHS.REPORTS.ACADEMIC.ROOT],
			},
			{
				id: "reports_finance",
				name: "Finance Reports",
				path: PATHS.REPORTS.FINANCE.ROOT,
				icon: PieChart,
				permissions: [PERMISSIONS.REPORTS.FINANCE.VIEW],
				matchPaths: [PATHS.REPORTS.FINANCE.ROOT],
			},
			{
				id: "reports_student",
				name: "Student Reports",
				path: PATHS.REPORTS.STUDENT.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.REPORTS.STUDENT.VIEW],
				matchPaths: [PATHS.REPORTS.STUDENT.ROOT],
			},
			{
				id: "reports_scheduled",
				name: "Scheduled Reports",
				path: PATHS.REPORTS.SCHEDULED.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.REPORTS.SCHEDULED.VIEW],
				matchPaths: [PATHS.REPORTS.SCHEDULED.ROOT],
			},
		],
	},
	{
		id: "roles",
		name: "Roles & Permissions",
		path: PATHS.ROLES.ROOT,
		icon: ShieldCheck,
		permissions: [PERMISSIONS.ROLES.VIEW],
		matchPaths: [PATHS.ROLES.ROOT],
		children: [
			{
				id: "roles_management",
				name: "Role Management",
				path: PATHS.ROLES.MANAGEMENT.ROOT,
				icon: ShieldCheck,
				permissions: [PERMISSIONS.ROLES.MANAGEMENT.VIEW],
				matchPaths: [PATHS.ROLES.MANAGEMENT.ROOT],
			},
			{
				id: "roles_matrix",
				name: "Permission Matrix",
				path: PATHS.ROLES.MATRIX.ROOT,
				icon: Network,
				permissions: [PERMISSIONS.ROLES.MATRIX.VIEW],
				matchPaths: [PATHS.ROLES.MATRIX.ROOT],
			},
		],
	},
	{
		id: "settings",
		name: "Settings",
		path: PATHS.SETTINGS.ROOT,
		icon: Settings,
		permissions: [PERMISSIONS.SETTINGS.VIEW],
		matchPaths: [PATHS.SETTINGS.ROOT],
		children: [
			{
				id: "settings_profile",
				name: "School Profile",
				path: PATHS.SETTINGS.PROFILE.ROOT,
				icon: School,
				permissions: [PERMISSIONS.SETTINGS.PROFILE.VIEW],
				matchPaths: [PATHS.SETTINGS.PROFILE.ROOT],
			},
			{
				id: "settings_users",
				name: "User Management",
				path: PATHS.SETTINGS.USERS.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.SETTINGS.USERS.VIEW],
				matchPaths: [PATHS.SETTINGS.USERS.ROOT],
			},
			{
				id: "settings_integrations",
				name: "Integration Settings",
				path: PATHS.SETTINGS.INTEGRATIONS.ROOT,
				icon: Link,
				permissions: [PERMISSIONS.SETTINGS.INTEGRATIONS.VIEW],
				matchPaths: [PATHS.SETTINGS.INTEGRATIONS.ROOT],
			},
			{
				id: "settings_localization",
				name: "Localization",
				path: PATHS.SETTINGS.LOCALIZATION.ROOT,
				icon: Globe,
				permissions: [PERMISSIONS.SETTINGS.LOCALIZATION.VIEW],
				matchPaths: [PATHS.SETTINGS.LOCALIZATION.ROOT],
			},
			{
				id: "settings_backup",
				name: "Data & Backup",
				path: PATHS.SETTINGS.BACKUP.ROOT,
				icon: Database,
				permissions: [PERMISSIONS.SETTINGS.BACKUP.VIEW],
				matchPaths: [PATHS.SETTINGS.BACKUP.ROOT],
			},
			{
				id: "settings_audit",
				name: "Audit Log",
				path: PATHS.SETTINGS.AUDIT.ROOT,
				icon: History,
				permissions: [PERMISSIONS.SETTINGS.AUDIT.VIEW],
				matchPaths: [PATHS.SETTINGS.AUDIT.ROOT],
			},
		],
	},
];
