import {
  Building2,
  BookOpen,
  GraduationCap,
  Users,
  Banknote,
  Library,
  Settings,
  LayoutDashboard,
  Megaphone,
  AlarmClockCheck,
  UserCheck,
  FileBadge2,
  UsersRound,
  Briefcase,
  ClipboardList,
  CalendarDays,
  Bus,
  Store,
  BarChart3,
  ShieldCheck,
  BookMarked,
  Laptop,
  User,
  TrendingUp,
  IdCard,
  Award,
  HeartHandshake,
  Network,
  BookType,
  Gift,
  PieChart,
  Receipt,
  Landmark,
  ArrowRightLeft,
  Coins,
  Clipboard,
  MessageSquare,
  AlertCircle,
  School,
  Link,
  Globe,
  Database,
  History,
  DoorOpen,
  Activity,
} from 'lucide-react';

import { PATHS } from './paths.config';
import { PERMISSIONS } from './permissions.config';

export type SidebarMenuType = {
  id: string;
  name: string;
  path: string;
  icon: React.ElementType;
  permissions: string[];
  matchPaths: string[];
  resetStore?: () => void;
  children?: SidebarMenuType[];
};

export const SidebarMenu: SidebarMenuType[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    path: PATHS.DASHBOARD,
    icon: LayoutDashboard,
    permissions: [PERMISSIONS.DASHBOARD.VIEW],
    matchPaths: [PATHS.DASHBOARD],
  },
  {
    id: 'academics',
    name: 'Academics',
    path: PATHS.ACADEMICS.ROOT,
    icon: BookOpen,
    permissions: [PERMISSIONS.ACADEMICS.VIEW],
    matchPaths: [PATHS.ACADEMICS.ROOT],
    children: [
      {
        id: 'academics_classes',
        name: 'Classes & Sections',
        path: PATHS.ACADEMICS.CLASSES,
        icon: Building2,
        permissions: [PERMISSIONS.ACADEMICS.CLASSES],
        matchPaths: [PATHS.ACADEMICS.CLASSES],
      },
      {
        id: 'academics_subjects',
        name: 'Subjects',
        path: PATHS.ACADEMICS.SUBJECTS,
        icon: BookOpen,
        permissions: [PERMISSIONS.ACADEMICS.SUBJECTS],
        matchPaths: [PATHS.ACADEMICS.SUBJECTS],
      },
      {
        id: 'academics_syllabus',
        name: 'Syllabus',
        path: PATHS.ACADEMICS.SYLLABUS,
        icon: FileBadge2,
        permissions: [PERMISSIONS.ACADEMICS.SYLLABUS],
        matchPaths: [PATHS.ACADEMICS.SYLLABUS],
      },
      {
        id: 'academics_timetable',
        name: 'Class Timetable',
        path: PATHS.ACADEMICS.TIMETABLE,
        icon: AlarmClockCheck,
        permissions: [PERMISSIONS.ACADEMICS.TIMETABLE],
        matchPaths: [PATHS.ACADEMICS.TIMETABLE],
      },
      {
        id: 'academics_homework',
        name: 'Homework & Assignments',
        path: PATHS.ACADEMICS.HOMEWORK,
        icon: BookMarked,
        permissions: [PERMISSIONS.ACADEMICS.HOMEWORK],
        matchPaths: [PATHS.ACADEMICS.HOMEWORK],
      },
      {
        id: 'academics_online_classes',
        name: 'Online Classes',
        path: PATHS.ACADEMICS.ONLINE_CLASSES,
        icon: Laptop,
        permissions: [PERMISSIONS.ACADEMICS.ONLINE_CLASSES],
        matchPaths: [PATHS.ACADEMICS.ONLINE_CLASSES],
      },
    ],
  },
  {
    id: 'admission',
    name: 'Admission Management',
    path: PATHS.ADMISSION.ROOT,
    icon: DoorOpen,
    permissions: [PERMISSIONS.ADMISSION.VIEW],
    matchPaths: [PATHS.ADMISSION.ROOT],
    children: [
      {
        id: 'admission_new',
        name: 'New Admission',
        path: PATHS.ADMISSION.NEW,
        icon: UserCheck,
        permissions: [PERMISSIONS.ADMISSION.NEW],
        matchPaths: [PATHS.ADMISSION.NEW],
      },
      {
        id: 'admission_list',
        name: 'Application List',
        path: PATHS.ADMISSION.LIST,
        icon: ClipboardList,
        permissions: [PERMISSIONS.ADMISSION.LIST],
        matchPaths: [PATHS.ADMISSION.LIST],
      },
      {
        id: 'admission_portal',
        name: 'Online Portal',
        path: PATHS.ADMISSION.PORTAL,
        icon: Globe,
        permissions: [PERMISSIONS.ADMISSION.PORTAL],
        matchPaths: [PATHS.ADMISSION.PORTAL],
      },
      {
        id: 'admission_transfer',
        name: 'Transfer Students',
        path: PATHS.ADMISSION.TRANSFER,
        icon: ArrowRightLeft,
        permissions: [PERMISSIONS.ADMISSION.TRANSFER],
        matchPaths: [PATHS.ADMISSION.TRANSFER],
      },
      {
        id: 'admission_settings',
        name: 'Admission Settings',
        path: PATHS.ADMISSION.SETTINGS,
        icon: Settings,
        permissions: [PERMISSIONS.ADMISSION.SETTINGS],
        matchPaths: [PATHS.ADMISSION.SETTINGS],
      },
    ],
  },
  {
    id: 'students',
    name: 'Students',
    path: PATHS.STUDENTS.ROOT,
    icon: GraduationCap,
    permissions: [PERMISSIONS.STUDENTS.VIEW],
    matchPaths: [PATHS.STUDENTS.ROOT],
    children: [
      {
        id: 'students_directory',
        name: 'Student Directory',
        path: PATHS.STUDENTS.DIRECTORY,
        icon: Users,
        permissions: [PERMISSIONS.STUDENTS.DIRECTORY],
        matchPaths: [PATHS.STUDENTS.DIRECTORY],
      },
      {
        id: 'students_attendance',
        name: 'Attendance',
        path: PATHS.STUDENTS.ATTENDANCE,
        icon: UserCheck,
        permissions: [PERMISSIONS.STUDENTS.ATTENDANCE],
        matchPaths: [PATHS.STUDENTS.ATTENDANCE],
      },
      {
        id: 'students_profile',
        name: 'Student Profile',
        path: PATHS.STUDENTS.PROFILE,
        icon: User,
        permissions: [PERMISSIONS.STUDENTS.PROFILE],
        matchPaths: [PATHS.STUDENTS.PROFILE],
      },
      {
        id: 'students_promotion',
        name: 'Class Promotion',
        path: PATHS.STUDENTS.PROMOTION,
        icon: TrendingUp,
        permissions: [PERMISSIONS.STUDENTS.PROMOTION],
        matchPaths: [PATHS.STUDENTS.PROMOTION],
      },
      {
        id: 'students_id_cards',
        name: 'ID Cards',
        path: PATHS.STUDENTS.ID_CARDS,
        icon: IdCard,
        permissions: [PERMISSIONS.STUDENTS.ID_CARDS],
        matchPaths: [PATHS.STUDENTS.ID_CARDS],
      },
      {
        id: 'students_certificates',
        name: 'Certificates',
        path: PATHS.STUDENTS.CERTIFICATES,
        icon: Award,
        permissions: [PERMISSIONS.STUDENTS.CERTIFICATES],
        matchPaths: [PATHS.STUDENTS.CERTIFICATES],
      },
      {
        id: 'students_behavior',
        name: 'Behavior & Counseling',
        path: PATHS.STUDENTS.BEHAVIOR,
        icon: HeartHandshake,
        permissions: [PERMISSIONS.STUDENTS.BEHAVIOR],
        matchPaths: [PATHS.STUDENTS.BEHAVIOR],
      },
    ],
  },
  {
    id: 'staff',
    name: 'Staff & Teachers',
    path: PATHS.STAFF.ROOT,
    icon: Users,
    permissions: [PERMISSIONS.STAFF.VIEW],
    matchPaths: [PATHS.STAFF.ROOT],
    children: [
      {
        id: 'staff_directory',
        name: 'Staff Directory',
        path: PATHS.STAFF.DIRECTORY,
        icon: Users,
        permissions: [PERMISSIONS.STAFF.DIRECTORY],
        matchPaths: [PATHS.STAFF.DIRECTORY],
      },
      {
        id: 'staff_attendance',
        name: 'Staff Attendance',
        path: PATHS.STAFF.ATTENDANCE,
        icon: UserCheck,
        permissions: [PERMISSIONS.STAFF.ATTENDANCE],
        matchPaths: [PATHS.STAFF.ATTENDANCE],
      },
      {
        id: 'staff_departments',
        name: 'Departments',
        path: PATHS.STAFF.DEPARTMENTS,
        icon: Network,
        permissions: [PERMISSIONS.STAFF.DEPARTMENTS],
        matchPaths: [PATHS.STAFF.DEPARTMENTS],
      },
      {
        id: 'staff_performance',
        name: 'Teacher Performance',
        path: PATHS.STAFF.PERFORMANCE,
        icon: Activity,
        permissions: [PERMISSIONS.STAFF.PERFORMANCE],
        matchPaths: [PATHS.STAFF.PERFORMANCE],
      },
    ],
  },
  {
    id: 'parents',
    name: 'Parents',
    path: PATHS.PARENTS.ROOT,
    icon: UsersRound,
    permissions: [PERMISSIONS.PARENTS.VIEW],
    matchPaths: [PATHS.PARENTS.ROOT],
    children: [
      {
        id: 'parents_directory',
        name: 'Parent Directory',
        path: PATHS.PARENTS.DIRECTORY,
        icon: UsersRound,
        permissions: [PERMISSIONS.PARENTS.DIRECTORY],
        matchPaths: [PATHS.PARENTS.DIRECTORY],
      },
      {
        id: 'parents_portal',
        name: 'Portal Access',
        path: PATHS.PARENTS.PORTAL,
        icon: Laptop,
        permissions: [PERMISSIONS.PARENTS.PORTAL],
        matchPaths: [PATHS.PARENTS.PORTAL],
      },
    ],
  },
  {
    id: 'finance',
    name: 'Finance',
    path: PATHS.FINANCE.ROOT,
    icon: Banknote,
    permissions: [PERMISSIONS.FINANCE.VIEW],
    matchPaths: [PATHS.FINANCE.ROOT],
    children: [
      {
        id: 'finance_fees',
        name: 'Fee Collection',
        path: PATHS.FINANCE.FEES,
        icon: Banknote,
        permissions: [PERMISSIONS.FINANCE.FEES],
        matchPaths: [PATHS.FINANCE.FEES],
      },
      {
        id: 'finance_expenses',
        name: 'Expenses',
        path: PATHS.FINANCE.EXPENSES,
        icon: Banknote,
        permissions: [PERMISSIONS.FINANCE.EXPENSES],
        matchPaths: [PATHS.FINANCE.EXPENSES],
      },
      {
        id: 'finance_payroll',
        name: 'Payroll',
        path: PATHS.FINANCE.PAYROLL,
        icon: Banknote,
        permissions: [PERMISSIONS.FINANCE.PAYROLL],
        matchPaths: [PATHS.FINANCE.PAYROLL],
      },
      {
        id: 'finance_ledger',
        name: 'Student Ledger',
        path: PATHS.FINANCE.LEDGER,
        icon: BookType,
        permissions: [PERMISSIONS.FINANCE.LEDGER],
        matchPaths: [PATHS.FINANCE.LEDGER],
      },
      {
        id: 'finance_scholarships',
        name: 'Scholarships & Waivers',
        path: PATHS.FINANCE.SCHOLARSHIPS,
        icon: Gift,
        permissions: [PERMISSIONS.FINANCE.SCHOLARSHIPS],
        matchPaths: [PATHS.FINANCE.SCHOLARSHIPS],
      },
      {
        id: 'finance_budget',
        name: 'Budget Planning',
        path: PATHS.FINANCE.BUDGET,
        icon: PieChart,
        permissions: [PERMISSIONS.FINANCE.BUDGET],
        matchPaths: [PATHS.FINANCE.BUDGET],
      },
      {
        id: 'finance_vouchers',
        name: 'Voucher Management',
        path: PATHS.FINANCE.VOUCHERS,
        icon: Receipt,
        permissions: [PERMISSIONS.FINANCE.VOUCHERS],
        matchPaths: [PATHS.FINANCE.VOUCHERS],
      },
      {
        id: 'finance_bank_accounts',
        name: 'Bank Accounts',
        path: PATHS.FINANCE.BANK_ACCOUNTS,
        icon: Landmark,
        permissions: [PERMISSIONS.FINANCE.BANK_ACCOUNTS],
        matchPaths: [PATHS.FINANCE.BANK_ACCOUNTS],
      },
    ],
  },
  {
    id: 'hr',
    name: 'HR Management',
    path: PATHS.HR.ROOT,
    icon: Briefcase,
    permissions: [PERMISSIONS.HR.VIEW],
    matchPaths: [PATHS.HR.ROOT],
    children: [
      {
        id: 'hr_leave',
        name: 'Leave Management',
        path: PATHS.HR.LEAVE,
        icon: CalendarDays,
        permissions: [PERMISSIONS.HR.LEAVE],
        matchPaths: [PATHS.HR.LEAVE],
      },
      {
        id: 'hr_loan',
        name: 'Loan & Advance',
        path: PATHS.HR.LOAN,
        icon: Banknote,
        permissions: [PERMISSIONS.HR.LOAN],
        matchPaths: [PATHS.HR.LOAN],
      },
      {
        id: 'hr_appraisal',
        name: 'Performance Appraisal',
        path: PATHS.HR.APPRAISAL,
        icon: Activity,
        permissions: [PERMISSIONS.HR.APPRAISAL],
        matchPaths: [PATHS.HR.APPRAISAL],
      },
    ],
  },
  {
    id: 'examinations',
    name: 'Examination & Results',
    path: PATHS.EXAMINATIONS.ROOT,
    icon: ClipboardList,
    permissions: [PERMISSIONS.EXAMINATIONS.VIEW],
    matchPaths: [PATHS.EXAMINATIONS.ROOT],
    children: [
      {
        id: 'examinations_schedule',
        name: 'Exam Schedule',
        path: PATHS.EXAMINATIONS.SCHEDULE,
        icon: CalendarDays,
        permissions: [PERMISSIONS.EXAMINATIONS.SCHEDULE],
        matchPaths: [PATHS.EXAMINATIONS.SCHEDULE],
      },
      {
        id: 'examinations_marks',
        name: 'Mark Entry',
        path: PATHS.EXAMINATIONS.MARKS,
        icon: FileBadge2,
        permissions: [PERMISSIONS.EXAMINATIONS.MARKS],
        matchPaths: [PATHS.EXAMINATIONS.MARKS],
      },
      {
        id: 'examinations_results',
        name: 'Result Processing',
        path: PATHS.EXAMINATIONS.RESULTS,
        icon: Activity,
        permissions: [PERMISSIONS.EXAMINATIONS.RESULTS],
        matchPaths: [PATHS.EXAMINATIONS.RESULTS],
      },
      {
        id: 'examinations_report_cards',
        name: 'Report Cards',
        path: PATHS.EXAMINATIONS.REPORT_CARDS,
        icon: ClipboardList,
        permissions: [PERMISSIONS.EXAMINATIONS.REPORT_CARDS],
        matchPaths: [PATHS.EXAMINATIONS.REPORT_CARDS],
      },
      {
        id: 'examinations_question_bank',
        name: 'Question Bank',
        path: PATHS.EXAMINATIONS.QUESTION_BANK,
        icon: BookOpen,
        permissions: [PERMISSIONS.EXAMINATIONS.QUESTION_BANK],
        matchPaths: [PATHS.EXAMINATIONS.QUESTION_BANK],
      },
      {
        id: 'examinations_settings',
        name: 'Exam Settings',
        path: PATHS.EXAMINATIONS.SETTINGS,
        icon: Settings,
        permissions: [PERMISSIONS.EXAMINATIONS.SETTINGS],
        matchPaths: [PATHS.EXAMINATIONS.SETTINGS],
      },
    ],
  },
  {
    id: 'library',
    name: 'Library',
    path: PATHS.LIBRARY.ROOT,
    icon: Library,
    permissions: [PERMISSIONS.LIBRARY.VIEW],
    matchPaths: [PATHS.LIBRARY.ROOT],
    children: [
      {
        id: 'library_catalog',
        name: 'Book Catalog',
        path: PATHS.LIBRARY.CATALOG,
        icon: BookOpen,
        permissions: [PERMISSIONS.LIBRARY.CATALOG],
        matchPaths: [PATHS.LIBRARY.CATALOG],
      },
      {
        id: 'library_issue_return',
        name: 'Issue & Return',
        path: PATHS.LIBRARY.ISSUE_RETURN,
        icon: ArrowRightLeft,
        permissions: [PERMISSIONS.LIBRARY.ISSUE_RETURN],
        matchPaths: [PATHS.LIBRARY.ISSUE_RETURN],
      },
      {
        id: 'library_fines',
        name: 'Fine Management',
        path: PATHS.LIBRARY.FINES,
        icon: Coins,
        permissions: [PERMISSIONS.LIBRARY.FINES],
        matchPaths: [PATHS.LIBRARY.FINES],
      },
      {
        id: 'library_reports',
        name: 'Library Reports',
        path: PATHS.LIBRARY.REPORTS,
        icon: BarChart3,
        permissions: [PERMISSIONS.LIBRARY.REPORTS],
        matchPaths: [PATHS.LIBRARY.REPORTS],
      },
    ],
  },
  {
    id: 'communications',
    name: 'Communications',
    path: PATHS.COMMUNICATIONS.ROOT,
    icon: Megaphone,
    permissions: [PERMISSIONS.COMMUNICATIONS.VIEW],
    matchPaths: [PATHS.COMMUNICATIONS.ROOT],
    children: [
      {
        id: 'communications_announcements',
        name: 'Announcements',
        path: PATHS.COMMUNICATIONS.ANNOUNCEMENTS,
        icon: Megaphone,
        permissions: [PERMISSIONS.COMMUNICATIONS.ANNOUNCEMENTS],
        matchPaths: [PATHS.COMMUNICATIONS.ANNOUNCEMENTS],
      },
      {
        id: 'communications_notice_board',
        name: 'Notice Board',
        path: PATHS.COMMUNICATIONS.NOTICE_BOARD,
        icon: Clipboard,
        permissions: [PERMISSIONS.COMMUNICATIONS.NOTICE_BOARD],
        matchPaths: [PATHS.COMMUNICATIONS.NOTICE_BOARD],
      },
      {
        id: 'communications_messages',
        name: 'Parent-Teacher Messaging',
        path: PATHS.COMMUNICATIONS.MESSAGES,
        icon: MessageSquare,
        permissions: [PERMISSIONS.COMMUNICATIONS.MESSAGES],
        matchPaths: [PATHS.COMMUNICATIONS.MESSAGES],
      },
      {
        id: 'communications_complaints',
        name: 'Complaints & Feedback',
        path: PATHS.COMMUNICATIONS.COMPLAINTS,
        icon: AlertCircle,
        permissions: [PERMISSIONS.COMMUNICATIONS.COMPLAINTS],
        matchPaths: [PATHS.COMMUNICATIONS.COMPLAINTS],
      },
    ],
  },
  {
    id: 'events',
    name: 'Events Management',
    path: PATHS.EVENTS.ROOT,
    icon: CalendarDays,
    permissions: [PERMISSIONS.EVENTS.VIEW],
    matchPaths: [PATHS.EVENTS.ROOT],
    children: [
      {
        id: 'events_scheduling',
        name: 'Event Scheduling',
        path: PATHS.EVENTS.SCHEDULING,
        icon: CalendarDays,
        permissions: [PERMISSIONS.EVENTS.SCHEDULING],
        matchPaths: [PATHS.EVENTS.SCHEDULING],
      },
      {
        id: 'events_participants',
        name: 'Participant Management',
        path: PATHS.EVENTS.PARTICIPANTS,
        icon: Users,
        permissions: [PERMISSIONS.EVENTS.PARTICIPANTS],
        matchPaths: [PATHS.EVENTS.PARTICIPANTS],
      },
      {
        id: 'events_gallery',
        name: 'Event Gallery',
        path: PATHS.EVENTS.GALLERY,
        icon: FileBadge2,
        permissions: [PERMISSIONS.EVENTS.GALLERY],
        matchPaths: [PATHS.EVENTS.GALLERY],
      },
    ],
  },
  {
    id: 'transport',
    name: 'Transport Management',
    path: PATHS.TRANSPORT.ROOT,
    icon: Bus,
    permissions: [PERMISSIONS.TRANSPORT.VIEW],
    matchPaths: [PATHS.TRANSPORT.ROOT],
    children: [
      {
        id: 'transport_routes',
        name: 'Route Management',
        path: PATHS.TRANSPORT.ROUTES,
        icon: Network,
        permissions: [PERMISSIONS.TRANSPORT.ROUTES],
        matchPaths: [PATHS.TRANSPORT.ROUTES],
      },
      {
        id: 'transport_vehicles',
        name: 'Vehicle Management',
        path: PATHS.TRANSPORT.VEHICLES,
        icon: Bus,
        permissions: [PERMISSIONS.TRANSPORT.VEHICLES],
        matchPaths: [PATHS.TRANSPORT.VEHICLES],
      },
      {
        id: 'transport_assignment',
        name: 'Student Assignment',
        path: PATHS.TRANSPORT.ASSIGNMENT,
        icon: Users,
        permissions: [PERMISSIONS.TRANSPORT.ASSIGNMENT],
        matchPaths: [PATHS.TRANSPORT.ASSIGNMENT],
      },
      {
        id: 'transport_attendance',
        name: 'Transport Attendance',
        path: PATHS.TRANSPORT.ATTENDANCE,
        icon: UserCheck,
        permissions: [PERMISSIONS.TRANSPORT.ATTENDANCE],
        matchPaths: [PATHS.TRANSPORT.ATTENDANCE],
      },
    ],
  },
  {
    id: 'canteen',
    name: 'Canteen / Tuck Shop',
    path: PATHS.CANTEEN.ROOT,
    icon: Store,
    permissions: [PERMISSIONS.CANTEEN.VIEW],
    matchPaths: [PATHS.CANTEEN.ROOT],
    children: [
      {
        id: 'canteen_menu',
        name: 'Menu Management',
        path: PATHS.CANTEEN.MENU,
        icon: ClipboardList,
        permissions: [PERMISSIONS.CANTEEN.MENU],
        matchPaths: [PATHS.CANTEEN.MENU],
      },
      {
        id: 'canteen_sales',
        name: 'Sales Tracking',
        path: PATHS.CANTEEN.SALES,
        icon: Banknote,
        permissions: [PERMISSIONS.CANTEEN.SALES],
        matchPaths: [PATHS.CANTEEN.SALES],
      },
      {
        id: 'canteen_expense',
        name: 'Canteen Expense',
        path: PATHS.CANTEEN.EXPENSE,
        icon: Banknote,
        permissions: [PERMISSIONS.CANTEEN.EXPENSE],
        matchPaths: [PATHS.CANTEEN.EXPENSE],
      },
    ],
  },
  {
    id: 'reports',
    name: 'Reports & Analytics',
    path: PATHS.REPORTS.ROOT,
    icon: BarChart3,
    permissions: [PERMISSIONS.REPORTS.VIEW],
    matchPaths: [PATHS.REPORTS.ROOT],
    children: [
      {
        id: 'reports_academic',
        name: 'Academic Reports',
        path: PATHS.REPORTS.ACADEMIC,
        icon: BarChart3,
        permissions: [PERMISSIONS.REPORTS.ACADEMIC],
        matchPaths: [PATHS.REPORTS.ACADEMIC],
      },
      {
        id: 'reports_finance',
        name: 'Finance Reports',
        path: PATHS.REPORTS.FINANCE,
        icon: PieChart,
        permissions: [PERMISSIONS.REPORTS.FINANCE],
        matchPaths: [PATHS.REPORTS.FINANCE],
      },
      {
        id: 'reports_student',
        name: 'Student Reports',
        path: PATHS.REPORTS.STUDENT,
        icon: Users,
        permissions: [PERMISSIONS.REPORTS.STUDENT],
        matchPaths: [PATHS.REPORTS.STUDENT],
      },
      {
        id: 'reports_scheduled',
        name: 'Scheduled Reports',
        path: PATHS.REPORTS.SCHEDULED,
        icon: CalendarDays,
        permissions: [PERMISSIONS.REPORTS.SCHEDULED],
        matchPaths: [PATHS.REPORTS.SCHEDULED],
      },
    ],
  },
  {
    id: 'roles',
    name: 'Roles & Permissions',
    path: PATHS.ROLES.ROOT,
    icon: ShieldCheck,
    permissions: [PERMISSIONS.ROLES.VIEW],
    matchPaths: [PATHS.ROLES.ROOT],
    children: [
      {
        id: 'roles_management',
        name: 'Role Management',
        path: PATHS.ROLES.MANAGEMENT,
        icon: ShieldCheck,
        permissions: [PERMISSIONS.ROLES.MANAGEMENT],
        matchPaths: [PATHS.ROLES.MANAGEMENT],
      },
      {
        id: 'roles_matrix',
        name: 'Permission Matrix',
        path: PATHS.ROLES.MATRIX,
        icon: Network,
        permissions: [PERMISSIONS.ROLES.MATRIX],
        matchPaths: [PATHS.ROLES.MATRIX],
      },
    ],
  },
  {
    id: 'settings',
    name: 'Settings',
    path: PATHS.SETTINGS.ROOT,
    icon: Settings,
    permissions: [PERMISSIONS.SETTINGS.VIEW],
    matchPaths: [PATHS.SETTINGS.ROOT],
    children: [
      {
        id: 'settings_profile',
        name: 'School Profile',
        path: PATHS.SETTINGS.PROFILE,
        icon: School,
        permissions: [PERMISSIONS.SETTINGS.PROFILE],
        matchPaths: [PATHS.SETTINGS.PROFILE],
      },
      {
        id: 'settings_users',
        name: 'User Management',
        path: PATHS.SETTINGS.USERS,
        icon: Users,
        permissions: [PERMISSIONS.SETTINGS.USERS],
        matchPaths: [PATHS.SETTINGS.USERS],
      },
      {
        id: 'settings_integrations',
        name: 'Integration Settings',
        path: PATHS.SETTINGS.INTEGRATIONS,
        icon: Link,
        permissions: [PERMISSIONS.SETTINGS.INTEGRATIONS],
        matchPaths: [PATHS.SETTINGS.INTEGRATIONS],
      },
      {
        id: 'settings_localization',
        name: 'Localization',
        path: PATHS.SETTINGS.LOCALIZATION,
        icon: Globe,
        permissions: [PERMISSIONS.SETTINGS.LOCALIZATION],
        matchPaths: [PATHS.SETTINGS.LOCALIZATION],
      },
      {
        id: 'settings_backup',
        name: 'Data & Backup',
        path: PATHS.SETTINGS.BACKUP,
        icon: Database,
        permissions: [PERMISSIONS.SETTINGS.BACKUP],
        matchPaths: [PATHS.SETTINGS.BACKUP],
      },
      {
        id: 'settings_audit',
        name: 'Audit Log',
        path: PATHS.SETTINGS.AUDIT,
        icon: History,
        permissions: [PERMISSIONS.SETTINGS.AUDIT],
        matchPaths: [PATHS.SETTINGS.AUDIT],
      },
    ],
  },
];